sudo: false
language: python
python:
  - "2.7"
  - "3.4"
before_script:
  # manually make our own virtualenv, so we don't need to worry about python version paths
  - deactivate
  - virtualenv .
  - source bin/activate
  - npm install less
  - npm install jshint
  - npm install recess
  - pip install -e .
  - pip install coverage
  - pip install mechanize
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  # This is for the server we'll run in the background...
  - mysql -u root -e 'create database sqlshare_rest_app'
  - mysql -u root -e 'create user "ss_rest_user" identified by "ss_pass"'
  - mysql -u root -e 'grant all on *.* to ss_rest_user'
  - mysql -u root -e 'grant grant option on *.* to ss_rest_user'
  - source travis-ci/start_rest_server.sh
  # Close out the virtual env from the rest server, go back to ours...
  - deactivate
  - ls -l
  - source bin/activate
  - python manage.py syncdb --noinput
  - python manage.py collectstatic  --noinput
  - python manage.py compress
script:
  - pep8 sqlshare_web/ --exclude=migrations,sqlshare_web/tests.py,sqlshare_web/test/
  - jshint sqlshare_web/static/sqlshare_web/js --verbose
  - RUN_SQLSHARE_VIEW_TESTS=1 coverage run --source=sqlshare_web/ --omit=sqlshare_rest/migrations/* manage.py test sqlshare_web
  - recess sqlshare_web/static/sqlshare_web/css/*.less --noIds false
  # This actually fails the test if there are recess errors :(
  - if recess sqlshare_web/static/sqlshare_web/css/*.less --noIds false | grep Busted | grep --quiet Busted ; then `exit 1`; fi
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
