language: python
python:
  - "2.7"
  - "3.4"
install: pip install -e .
before_script:
  - npm install less
  - npm install jshint
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
  - python manage.py collectstatic  --noinput
  - python manage.py compress
script:
  - pep8 sqlshare_web/ --exclude=migrations,sqlshare_web/tests.py,sqlshare_web/test/
  - jshint sqlshare_web/static/sqlshare_web/js --verbose
  - coverage run --source=sqlshare_web/ --omit=sqlshare_rest/migrations/* manage.py test sqlshare_web
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
